# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HappySNS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HappySNS

  target 'HappySNSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HappySNSUITests' do
    # Pods for testing
  end

pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Storage' 
pod 'Firebase/Firestore'
pod 'RAMAnimatedTabBarController'
pod "ViewAnimator"
end
